### ISSUE TITLE
Journey OST

### ISSUE THREAD

**Issue by dekadentno** [sarthology/ProjectSoundtracks#16]
### Journey OST 🦇
🎼 **Music Composer:**  Austin Wintory

👍🏻 **Best for:**  High Concentration Works 🔥

🔗 **Links:** [Youtube](https://www.youtube.com/watch?v=M3hFN8UrBPw)

**Comment by sarthology** [comment]
That's an Awesome playlist.

**Comment by sarthology** [comment]
Please submit a pull request. 😊
