### ISSUE TITLE
Melophobia- Cage the Elephant

### ISSUE THREAD

**Issue by asaw4** [sarthology/ProjectSoundtracks#19]
### Melophobia  🦇
🎼 **Music Composer:**  Cage the Elephant 

👍🏻 **Best for:**  Lightening your mood 

🔗 **Links:**  [Spotify](https://open.spotify.com/album/4EK8gtQfdVsmDTji7gBFlz), [Apple Music](https://music.apple.com/us/album/melophobia/683346293) , [Youtube](https://www.youtube.com/playlist?list=OLAK5uy_kdMzcHs_e8Bfxkcuy-TxFmwqoUGxtqAYg)

**Comment by Mustafiz04** [comment]
You created an issue. You should have to create a pull request. So that they can merge this into the original.

**Comment by vlvagerviwager** [comment]
This has been merged: https://github.com/sarthology/ProjectSoundtracks/pull/28.

**Comment by vlvagerviwager** [comment]
Just spotted [this](https://github.com/sarthology/ProjectSoundtracks/pull/20#issuecomment-603291337), this suggestion was rejected before, therefore I will revert.
